server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootflyway?autoReconnect=true&useSSL=false
    username : root
    password : 1234
    driver-class-name : com.mysql.jdbc.Driver
  jackson:
    generator:
      write_bigdecimal_as_plain: true